### PR TITLE
User story/us i os 0004 offer ride

### PR DESCRIPTION
**Pull request by Taxxodium**
- added UI for Offer Ride screen
- added functionality to Offer Ride screen
- added unit tests for Offer Ride screen

### CODE REVIEW

**Comment by Taxxodium** [comment]
New build with corrections on all screens and bug fixes!

**Comment by Taxxodium** [comment]
PR4: bug fixes and small additions

**Comment by Fgosch** [comment]
All comments, request and testcases under the scope of the user story were achieved.

**Comment by Taxxodium** [comment]
PR5: bug fix in profile when leaving a field empty

**Pull request merged**
